//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCoffe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOIMON
    {
        public int MaGoiMon { get; set; }
        public int MaBan { get; set; }
        public int MaMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DANHSACHBAN DANHSACHBAN { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
